# Generated by Django 3.2.25 on 2024-05-27 22:10

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=item.models.item_image_file_path),
        ),
    ]
