# Generated by Django 3.2.25 on 2024-05-27 22:37

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_image'),
    ]

    operations = [
        TrigramExtension(),
    ]
