# Generated by Django 3.2.25 on 2024-05-27 23:54

from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20240527_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=item.models.item_image_file_path),
        ),
        migrations.RemoveField(
            model_name='item',
            name='marca',
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.brand'),
        ),
    ]
