# Generated by Django 3.2.25 on 2024-05-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20240527_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_on_loan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
