# Generated by Django 3.2.25 on 2024-05-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('own_password_modification', "Modification of self's account password"), ('own_phone_modification', "Modification of self's account phone number")]},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='role_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='role_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabAdmin',
            fields=[
            ],
            options={
                'permissions': [('lab_admin_creation', 'Creation of lab admin users'), ('lab_admin_modification', 'Modification of lab admin users'), ('assistant_inactivation', 'Deletion of assistant users'), ('assistant_modification', 'Modification of assistant users'), ('assistant_creation', 'Creation of assistan users')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.role',),
        ),
        migrations.CreateModel(
            name='LabAssistant',
            fields=[
            ],
            options={
                'permissions': [],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.role',),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
