# Generated by Django 3.2.25 on 2024-05-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_auto_20240507_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='role_set', related_query_name='role', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='role_set', related_query_name='role', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
