# Generated by Django 3.2.25 on 2024-05-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
