# Generated by Django 3.2.25 on 2024-08-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('publica', models.BooleanField()),
                ('capacidad', models.IntegerField()),
                ('foto', models.CharField(max_length=255)),
                ('cancelada', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('enlace', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenciaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.categoria')),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conferencia')),
            ],
        ),
        migrations.AddField(
            model_name='conferencia',
            name='categoria',
            field=models.ManyToManyField(through='conference.ConferenciaCategoria', to='conference.Categoria'),
        ),
    ]
